[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = { version = "0.1.0", path = "../grid" }
regex = "1.11.1"
scan_fmt = "0.2.6"